name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
      - develop
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir dist
          cp -R src/* dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
